language: julia
os:
  - linux

julia:
  - 1

before_script:
  - git config --global user.name "GitUser"
  - git config --global user.email "git@us.er"

jobs:
  fast_finish: true
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
notifications:
  email: false
